106 hello thread exercise demo
bobocode-projects/java-fundamentals-course pull request #114
Opened 2021-10-15 13:53 UTC by tkuzub

2021-11-05 11:32 UTC, tboychuk requested changes
@tkuzub please take a look at my comments. Thank you!

2021-11-05 11:32 UTC, tboychuk commented on pom.xml
> +        <module>7-0-java-concurrency</module>
@tkuzub 
* please move this line up (right after the 6th module)
* please remove the next line (you should follow the same approach we have), in other words, **this pom file declares only high-level modules**. And `7-0-0-hello-threads` should be declared as a submodule of `7-0-java-concurrency` inside its pom file.

2021-11-05 11:32 UTC, tboychuk commented on 7-0-java-concurrency/7-0-0-hello-threads/pom.xml
> +    <artifactId>7-0-0-hello-theads</artifactId>
@tkuzub there is a mistake here: it should be `7-0-0-hello-threads` not `7-0-0-hello-theads`

2021-11-05 11:32 UTC, tboychuk commented on 7-0-java-concurrency/7-0-0-hello-threads/src/main/java/HelloThreads.java
> +public class HelloThreads {
@tkuzub a class should have a javadoc as well. For instance

```
/**
 * {@link HelloThreads} provide a simple API for working with Java threads. A {@link Thread} class represents a key
 * concept in Java Concurrency. So this class is meant to teach you the basics like creating a thread or checking its
 * state.
 * <p>
 * todo: implement each method according to javadoc and verify your impl by running {@link HelloThreadsTest}
 *
 * @author Taras Kuzub
 */
```

2021-11-05 11:32 UTC, tboychuk commented on 7-0-java-concurrency/7-0-0-hello-threads/src/main/java/HelloThreads.java
> +    public static List<Thread> runInMultipleThreads(Runnable runnable) {
@tkuzub let's better add another parameter to specify the number of threads.

2021-11-05 11:32 UTC, tboychuk commented on 7-0-java-concurrency/7-0-0-hello-threads/src/test/java/HelloThreadsTest.java
> +        verifyContentQueue();
@tkuzub I don't like this approach with a shared queue. I guess it's better that you create a new instance of a queue in each test if you need and, then use it, and then verify what you want to verify.

2021-11-05 11:32 UTC, tboychuk commented on 7-0-java-concurrency/7-0-0-hello-threads/src/test/java/HelloThreadsTest.java
> +        verifyContentQueue();
It should not assert the queue content, since this method is only created to the thread name.

2021-11-05 11:32 UTC, tboychuk commented on 7-0-java-concurrency/7-0-0-hello-threads/src/test/java/HelloThreadsTest.java
> +        verifyContentQueue();
It should not assert the queue content.

2021-11-05 11:32 UTC, tboychuk commented on 7-0-java-concurrency/7-0-0-hello-threads/src/test/java/HelloThreadsTest.java
> +
@tkuzub every test should follow the patter 
* **build** – where you prepare everything you need
* **operate** - where you perform the action that you want to test
* **assert** - where you verify the results and check if they are correct 
Another similar pattern is **given, when, then**.

For the assertions we use AsserJ. So for example the following test should look like this:
```java
    @SneakyThrows
    @Test
    @Order(3)
    void getThreadState() {
        var thread = new Thread(waitASecond());
        thread.start();
        
        var state = HelloThreads.getThreadState(thread);

        assertThat(state).isEqualTo(RUNNABLE);
    }
```

2021-11-05 11:32 UTC, tboychuk commented on 7-0-java-concurrency/7-0-0-hello-threads/src/main/java/HelloThreads.java
> +import com.bobocode.util.ExerciseNotCompletedException;
@tkuzub please move all the code to package `com.bobocode.concurrency`

2022-06-27 08:07 UTC, tboychuk commented
@tkuzub it looks like there is no progress on this task. I'm going to close this PR if you don't mind.

2022-06-27 08:18 UTC, tkuzub commented
>

2022-06-27 08:18 UTC, closed without merging